language: node_js
node_js:
  - "11.0.0"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g angular-cli

script:
  - npm run-script build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/consulting-web-app
  on:
    branch: master