language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - ng build --prod --base-href \"https://Xenon-Labs.github.io/website/\" && echo xenonlabs.ca > dist/consulting-web-app/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/consulting-web-app
  on:
    branch: master